### PR TITLE
Windows Terminal port

### PR DESCRIPTION
**Pull request by ghost**
I created a Windows Terminal port for Daycula. Let me know what you think and please tell me if something doesn't look right. 

[windows_terminal_daycula.txt](https://github.com/ghifarit53/daycula-vim/files/5954652/windows_terminal_daycula.txt)

### CODE REVIEW

**Comment by ghifarit53** [comment]
Hi @claytod5, thanks for creating PR and sorry for the very long wait because I've been busy this few weeks.
At the moment, I don't have any Windows machine to test it, so would you mind if you provide a screenshot with script like `neofetch` or https://github.com/stark/Color-Scripts so I can see how it looks

**Comment by ghost** [comment]
windows_terminal_screenshot

Here ya go. I'm open to criticism.

**Comment by ghost** [comment]
windows_terminal_screenshot2

Here is another one with the full Windows Terminal window in view. I censored the hostname and username, in case you are wondering about the black boxes.

**Comment by ghifarit53** [comment]
Looks gorgeous! Thank you

**Pull request merged**
